[package]

name = "err"
version = "0.0.4"
authors = ["Cody P Schafer <dev@codyps.com>"]
license = "MIT"
repository = "https://github.com/jmesmon/rust-err"
description = "A few macros & misc that make using rust's Error infrastructure more convenient"
